apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-chrome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-chrome
  template:
    metadata:
      labels:
        app: selenium-chrome
    spec:
      containers:
        - name: selenium-chrome
          image: alibayovsh/selenium-chrome:v2
          ports:
            - containerPort: 4444
          env:
            - name: SE_NODE_SESSION_TIMEOUT
              value: "300"
            - name: SE_NODE_MAX_SESSIONS
              value: "1"
          resources:
            requests:
              memory: "1Gi"
              cpu: "1"
            limits:
              memory: "2Gi"
              cpu: "2"
---
apiVersion: v1
kind: Service
metadata:
  name: selenium-chrome
spec:
  selector:
    app: selenium-chrome
  ports:
    - protocol: TCP
      port: 4444
      targetPort: 4444
  type: ClusterIP
